### ISSUE TITLE
 Sizes of tensors must match except in dimension 1. Got 45 and 46 in dimension 2 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THC/generic/THCTensorMath.cu:71

### ISSUE THREAD

**Issue by qianjinhao** [qubvel/segmentation_models.pytorch#196]
when I run the example , I got this error:
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    train()
  File "train.py", line 140, in train
    train_logs = train_epoch.run(train_loader)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 47, in run
    loss, y_pred = self.batch_update(x, y)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/utils/train.py", line 87, in batch_update
    prediction = self.model.forward(x)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/base/model.py", line 16, in forward
    decoder_output = self.decoder(*features)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/unet/decoder.py", line 119, in forward
    x = decoder_block(x, skip)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/qianjinhao/anaconda3cn10/envs/open-mmlab/lib/python3.7/site-packages/segmentation_models_pytorch/unet/decoder.py", line 38, in forward
    x = torch.cat([x, skip], dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 45 and 46 in dimension 2 at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THC/generic/THCTensorMath.cu:71

**Comment by JulienMaille** [comment]
What is the size of your images/masks?

**Comment by qianjinhao** [comment]
> What is the size of your images/masks?

 720,1080 Is it related to the size of the image?

**Comment by JulienMaille** [comment]
I think so. Images shall be a multiple of 32 since they will be subsampled 5 times

**Comment by qianjinhao** [comment]
> I think so. Images shall be a multiple of 32 since they will be subsampled 5 times

Thanks

**Comment by theidealist2** [comment]
> I think so. Images shall be a multiple of 32 since they will be subsampled 5 times

thanks!
