### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'Lambda'

### ISSUE THREAD

**Issue by yangyang117** [qubvel/segmentation_models.pytorch#457]
I want to know which version of albumentations is used for this program?

**Comment by yangyang117** [comment]
there is also another problem ：
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 54, in __getitem__
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/albumentations/core/composition.py", line 132, in __call__
    data = t(**data)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/albumentations/imgaug/transforms.py", line 22, in __call__
    return super(BasicIAATransform, self).__call__(**kwargs)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 28, in __call__
    params = self.update_params(params, **kwargs)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/albumentations/imgaug/transforms.py", line 26, in update_params
    params['deterministic_processor'] = self.processor.to_deterministic()
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/albumentations/imgaug/transforms.py", line 255, in processor
    return iaa.PerspectiveTransform(self.scale, self.keep_size)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/imgaug/augmenters/geometric.py", line 3567, in __init__
    self.cval = _handle_cval_arg(cval)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/imgaug/augmenters/geometric.py", line 132, in _handle_cval_arg
    list_to_choice=True)
  File "/home/yyang2/data/yyang2/anaconda/envs/mctrans/lib/python3.7/site-packages/imgaug/parameters.py", line 102, in handle_continuous_param
    allowed_type, allowed_type, list_str, name, type(param),))
Exception: Expected number, tuple of two number, list of number or StochasticParameter for cval, got <class 'bool'>.

**Comment by johnahjohn** [comment]
i too getting this error AttributeError: module 'albumentations' has no attribute 'Lambda'. how to fix this issue
