### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'groups'

### ISSUE THREAD

**Issue by LitvinchukAndrey** [qubvel/segmentation_models.pytorch#64]
I downloaded new version of library from source :
```pip install git+https://github.com/qubvel/segmentation_models.pytorch```
And now i have this problem : 
```TypeError: __init__() got an unexpected keyword argument 'groups'```

Full error : 
```Traceback (most recent call last):
  File "segmentation_model.py", line 235, in <module>
    defect_crop=args.defect_crop)
  File "segmentation_model.py", line 166, in train
    model = get_model(model_name=model_name, encoder_name=encoder).to(device)
  File "segmentation_model.py", line 98, in get_model
    model = FPN(encoder_name=encoder_name, classes=4, activation='sigmoid', encoder_weights=encoder_weights)
  File "/home/andrii/.conda/envs/dev/lib/python3.7/site-packages/segmentation_models_pytorch/fpn/model.py", line 39, in __init__
    encoder_weights=encoder_weights
  File "/home/andrii/.conda/envs/dev/lib/python3.7/site-packages/segmentation_models_pytorch/encoders/__init__.py", line 24, in get_encoder
    encoder = Encoder(**encoders[name]['params'])
  File "/home/andrii/.conda/envs/dev/lib/python3.7/site-packages/segmentation_models_pytorch/encoders/resnet.py", line 10, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'groups'
````

**Comment by qubvel** [comment]
Hi, please update torchvision to 0.3.0

**Comment by LitvinchukAndrey** [comment]
Thanks!
