### ISSUE TITLE
Custom encoder - 'Wrong pretrained weights `imagenet` for encoder `test`

### ISSUE THREAD

**Issue by eagle20-k** [qubvel/segmentation_models.pytorch#718]
I want to write my own encoder in order to deploy a simple Unet Architecture with SMP. I do not want to use any pretrained weights for my model training. 
My problem is, that I do not see where I can specify that. When running the code like in the [docs](https://smp.readthedocs.io/en/latest/insights.html) and shown in [other issues](https://github.com/qubvel/segmentation_models.pytorch/issues/571), I get asked for pretrained weights. 

Thank you for helping!

When running the `TestEncoder`, I get following error message: 
```
Traceback (most recent call last):
  File "C:\ProgramData\Miniforge3\envs\campsemseg\lib\site-packages\segmentation_models_pytorch\encoders\__init__.py", line 72, in get_encoder
    settings = encoders[name]["pretrained_settings"][weights]
KeyError: 'imagenet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Wernicke\camp_semseg\Develop_Code_Here.py", line 80, in <module>
    model = smp.Unet(encoder_name="test")
  File "C:\ProgramData\Miniforge3\envs\campsemseg\lib\site-packages\segmentation_models_pytorch\decoders\unet\model.py", line 71, in __init__
    self.encoder = get_encoder(
  File "C:\ProgramData\Miniforge3\envs\campsemseg\lib\site-packages\segmentation_models_pytorch\encoders\__init__.py", line 74, in get_encoder
    raise KeyError(
KeyError: 'Wrong pretrained weights `imagenet` for encoder `test`. Available options are: []'
```

And my code is as following: 

```

class conv_block(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv1 = nn.Conv2d(in_c, out_c, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(out_c)
        self.conv2 = nn.Conv2d(out_c, out_c, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(out_c)
        self.relu = nn.ReLU()

    def forward(self, inputs):
        x = self.conv1(inputs)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = self.relu(x)
        return x


class encoder_block(nn.Module):
    def __init__(self, in_c, out_c):
        super().__init__()
        self.conv = conv_block(in_c, out_c)
        self.pool = nn.MaxPool2d((2, 2))

    def forward(self, inputs):
        x = self.conv(inputs)
        p = self.pool(x)
        return x, p


class TestEncoder(nn.Module, smp.encoders._base.EncoderMixin):
    def __init__(self, **params):
        super().__init__()
        # A number of channels for each encoder feature tensor, list of integers
        self._out_channels = [3, 64, 128, 256, 512, 1024]
        # A number of stages in decoder (in other words number of downsampling operations), integer
        # use in forward pass to reduce number of returning features
        self._depth: int = 5
        # Default number of input channels in first Conv2d layer for encoder (usually 3) (here I could also try 4)
        self._in_channels: int = 3
        # self._weights = None
        # self.pretrained = None

    def forward(self, x):
        ftrs = []
        for block in encoder_block(self._in_channels, self._out_channels):
            x = block(x)
            ftrs.append(x)
            x = self.pool(x)
        return ftrs


smp.encoders.encoders["test"] = {
    "encoder": TestEncoder,  # encoder class here
    "pretrained_settings": {},
    "params": {},
}
model = smp.Unet(encoder_name="test")
```

**Comment by eagle20-k** [comment]
Simple answer: 
```
model = smp.Unet(encoder_name="test", encoder_weights=None)
```
